apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: infrabox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      tolerations:
        - key: infrabox-role
          operator: Equal
          value: api
          effect: NoSchedule
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
          args:
            - --provider=google
            - --upstream=file:///dev/null
            - --http-address=0.0.0.0:4180
            - --reverse-proxy=true
            - --skip-provider-button=true
            - --cookie-secure=true
            - --cookie-samesite=lax
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secret
                  key: client-id
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secret
                  key: client-secret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secret
                  key: cookie-secret
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secret
                  key: email-domain
            - name: OAUTH2_PROXY_COOKIE_DOMAINS
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secret
                  key: cookie-domain
            - name: OAUTH2_PROXY_WHITELIST_DOMAINS
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secret
                  key: cookie-domain
          ports:
            - containerPort: 4180
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-svc
  namespace: infrabox
spec:
  selector:
    app: oauth2-proxy
  ports:
    - port: 4180
      targetPort: 4180
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy-ingress
  namespace: infrabox
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - AUTH_DOMAIN_PLACEHOLDER
      secretName: tls-oauth2-proxy
  rules:
    - host: AUTH_DOMAIN_PLACEHOLDER
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy-svc
                port:
                  number: 4180
